Bump v0.25.0-1
NordSecurity/uniffi-generators pull request #9
Opened 2023-11-16 13:10 UTC by arg0d

2023-11-16 13:44 UTC, arg0d commented on compatibility-test/tests/go/coverall_test.go
>   * License, v. 2.0. If a copy of the MPL was not distributed with this
I'm not sure what happened here. At first I though it was tabs/spaces, but even when matching tabs/spaces, it was still showing diff. I guess it was newlines? :thinking:

2023-11-16 13:56 UTC, Lipt0nas commented on compatibility-test/tests/cs/test_coverall.cs
> +            Assert.Equal(2UL, coveralls.StrongCount());
```suggestion
            Assert.Equal(2UL, coveralls.StrongCount());
```

2023-11-21 09:43 UTC, Lipt0nas approved these changes

2023-11-21 11:07 UTC, Savolro requested changes

2023-11-21 11:22 UTC, Savolro approved these changes

2023-11-21 11:24 UTC, arg0d commented on Dockerfile
> +RUN cargo install uniffi-bindgen-cpp --tag v0.1.0+v0.25.0 --git https://github.com/NordSecurity/uniffi-bindgen-cpp
This ballooned from my initial basic change to just add C++ :sweat_smile: Gonna keep it like this, and as we discussed in PM investigate the option to deduplicate `compatibility-test` to use upstream code directly without copying the tests into this repo.

2023-11-21 11:27 UTC, arg0d commented on Dockerfile
> +RUN cargo install uniffi-bindgen-cpp --tag v0.1.0+v0.25.0 --git https://github.com/NordSecurity/uniffi-bindgen-cpp
https://github.com/NordSecurity/uniffi-generators/issues/10

2023-11-21 11:28 UTC, merged